### ISSUE TITLE
HERE configure info disappeared after console closed

### ISSUE THREAD

**Issue by nuistzhou** [heremaps/here-cli#40]
I have tried to set my configuration information many times with either way below: 

**here configure set** 
OR
**here configure account**

And it always succeeds and I was able to list all my spaces properly! :D

But the thing is that, once I close my console (tried on both Mac OS and Ubuntu 18) and open it again, the following error msg pops up after I typed in the command "here xyz list":

```
Failed to login : {"message":"No such token exists.","streamId":"640769ad-4686-11e9-ab56-91c5b76fa36e"}
(node:25269) UnhandledPromiseRejectionWarning: Error: Failed to log in
    at /usr/local/lib/node_modules/@here/cli/bin/common.js:122:19
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@here/cli/bin/common.js:27:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:25269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25269) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by burritojustice** [comment]
thanks Ping, we'll look into this.

**Comment by nuistzhou** [comment]
No worry, seems working now...
